"""
Shared schema package for the Robco BIM platform.
All services import contract types from here — never redefine locally.
Implements: System Contracts Document (all entity contracts)
"""

from .health import HealthResponse
from .gateway import InferenceRequest, InferenceResponse
from .ingestion import IngestionRequest, IngestionResponse
from .domain import (
    BuildingElement,
    DocumentChunk,
    Issue,
    ScheduleRow,
    MarkupRecord,
)
from .workflow import WorkflowRun, WorkflowStep, WorkflowStatus
from .deliverable import Deliverable
from .memory import MemoryNote
from .usage import UsageEvent
from .maternal import (
    MaternalCheckin,
    MaternalCheckinCreate,
    MaternalDashboard,
    MaternalProfile,
    MaternalProfileCreate,
    MaternalResource,
)
from .admin import (
    AdminAlert,
    AdminDashboardResponse,
    DailyUsage,
    OutreachPerformance,
    QueueStatus,
    SanitizerEvent,
    SanitizerPolicy,
    SanitizerPolicyUpdate,
    SanitizerSummary,
    ServiceBreakdown,
    TenantCreate,
    TenantAPIKeyCreateResponse,
    TenantAPIKeyResponse,
    TenantResponse,
    TenantUpdate,
    UsageRollup,
    WorkflowHealth,
)
from .gtm import (
    GTMActivityItem,
    GTMCampaign,
    GTMCampaignLaunchRequest,
    GTMConversion,
    GTMOfferDecision,
    GTMOfferCatalogItem,
    GTMOperatorDashboard,
    GTMOpportunity,
    GTMProposalRequest,
    GTMProofAsset,
    GTMProvisioningStatus,
    GTMReply,
    GTMReplyClassifyRequest,
    GTMReplyClassifyResponse,
    GTMSalesAction,
    GTMSuppressionEntry,
    GTMTarget,
    GTMTargetCreate,
    GTMTargetDetail,
    GTMTargetImportRequest,
    GTMTargetScore,
)
from .billing import BillingCheckoutCreate, BillingCheckoutResponse

__all__ = [
    "HealthResponse",
    "InferenceRequest",
    "InferenceResponse",
    "IngestionRequest",
    "IngestionResponse",
    "BuildingElement",
    "DocumentChunk",
    "Issue",
    "ScheduleRow",
    "MarkupRecord",
    "WorkflowRun",
    "WorkflowStep",
    "WorkflowStatus",
    "Deliverable",
    "MemoryNote",
    "UsageEvent",
    "MaternalProfileCreate",
    "MaternalProfile",
    "MaternalCheckinCreate",
    "MaternalCheckin",
    "MaternalResource",
    "MaternalDashboard",
    "AdminAlert",
    "AdminDashboardResponse",
    "DailyUsage",
    "OutreachPerformance",
    "QueueStatus",
    "SanitizerEvent",
    "SanitizerPolicy",
    "SanitizerPolicyUpdate",
    "SanitizerSummary",
    "ServiceBreakdown",
    "TenantCreate",
    "TenantAPIKeyCreateResponse",
    "TenantAPIKeyResponse",
    "TenantResponse",
    "TenantUpdate",
    "UsageRollup",
    "WorkflowHealth",
    "GTMTarget",
    "GTMTargetCreate",
    "GTMTargetImportRequest",
    "GTMTargetScore",
    "GTMOfferDecision",
    "GTMOfferCatalogItem",
    "GTMProofAsset",
    "GTMSalesAction",
    "GTMConversion",
    "GTMCampaign",
    "GTMReply",
    "GTMSuppressionEntry",
    "GTMCampaignLaunchRequest",
    "GTMReplyClassifyRequest",
    "GTMReplyClassifyResponse",
    "GTMProposalRequest",
    "GTMActivityItem",
    "GTMOpportunity",
    "GTMProvisioningStatus",
    "GTMTargetDetail",
    "GTMOperatorDashboard",
    "BillingCheckoutCreate",
    "BillingCheckoutResponse",
]
