options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/robco-containers/arkhamprison:$COMMIT_SHA'
      - -t
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/robco-containers/arkhamprison:latest'
      - -f
      - apps/web/Dockerfile
      - --build-arg
      - VITE_GATEWAY_URL=https://api.arkhamprison.com
      - apps/web
    id: build

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - --all-tags
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/robco-containers/arkhamprison'
    id: push
    waitFor: [build]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - arkhamprison
      - --image=us-central1-docker.pkg.dev/${PROJECT_ID}/robco-containers/arkhamprison:$COMMIT_SHA
      - --region=us-central1
      - --project=${PROJECT_ID}
      - --allow-unauthenticated
      - --port=80
      - --memory=256Mi
      - --cpu=1
      - --max-instances=3
    id: deploy
    waitFor: [push]

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/robco-containers/arkhamprison:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/robco-containers/arkhamprison:latest'
