#!/usr/bin/env bash
#
# new_vertical.sh — Scaffold a new vertical for the Arkham hub-and-spoke platform.
#
# Usage:
#   ./infra/scripts/new_vertical.sh <vertical_name> [port] [capabilities...]
#
# Examples:
#   ./infra/scripts/new_vertical.sh data_explorer 3110 search analytics
#   ./infra/scripts/new_vertical.sh my_tool 3120
#
set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <vertical_name> [port] [capabilities...]"
    echo "  vertical_name  snake_case name (e.g. data_explorer)"
    echo "  port           external port (default: auto-assign next available)"
    echo "  capabilities   space-separated list of capabilities"
    exit 1
fi

VERTICAL_NAME="$1"
PORT="${2:-0}"
shift; shift 2>/dev/null || true
CAPABILITIES=("$@")

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VERTICAL_DIR="$REPO_ROOT/services/verticals/$VERTICAL_NAME"

# ── Validate ─────────────────────────────────────────────────────────────────

if [ -d "$VERTICAL_DIR" ]; then
    echo "ERROR: Vertical '$VERTICAL_NAME' already exists at $VERTICAL_DIR"
    exit 1
fi

# Auto-assign port if not provided
if [ "$PORT" = "0" ]; then
    # Find highest port in docker-compose and add 10
    PORT=$(grep -oP '"\K\d+(?=:8000")' "$REPO_ROOT/docker-compose.yml" | sort -n | tail -1)
    PORT=$((PORT + 10))
    echo "Auto-assigned port: $PORT"
fi

# Format capabilities as Python list
if [ ${#CAPABILITIES[@]} -gt 0 ]; then
    CAP_STR=$(printf ', "%s"' "${CAPABILITIES[@]}")
    CAP_STR="[${CAP_STR:2}]"
else
    CAP_STR='[]'
fi

# Pretty title
TITLE=$(echo "$VERTICAL_NAME" | sed 's/_/ /g' | sed 's/\b\(.\)/\u\1/g')

# Docker service name (hyphens)
SERVICE_NAME=$(echo "$VERTICAL_NAME" | tr '_' '-')

# ── Create directory structure ───────────────────────────────────────────────

echo "Creating vertical: $VERTICAL_NAME"
mkdir -p "$VERTICAL_DIR/app"
touch "$VERTICAL_DIR/app/__init__.py"

# ── main.py ──────────────────────────────────────────────────────────────────

cat > "$VERTICAL_DIR/app/main.py" << PYEOF
"""
${TITLE} Vertical
Auto-generated by new_vertical.sh — customize as needed.
"""

from typing import Any, Dict

from packages.vertical_base import EventPayload, VerticalBase

vertical = VerticalBase(
    service_id="${VERTICAL_NAME}",
    title="${TITLE}",
    port=8000,
    capabilities=${CAP_STR},
    event_subscriptions=[],  # Add event types to listen for
)

app = vertical.app


# ── Event Handlers ───────────────────────────────────────────────────────────
# Uncomment and customize:
#
# @vertical.on_event("some.event.type")
# async def handle_event(event: EventPayload):
#     print(f"Received: {event.event_type} from {event.source_service}")


# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/")
async def root():
    return {"service": "${VERTICAL_NAME}", "status": "operational"}
PYEOF

# ── requirements.txt ─────────────────────────────────────────────────────────

cat > "$VERTICAL_DIR/requirements.txt" << 'REQEOF'
fastapi==0.109.0
uvicorn[standard]==0.27.0
pydantic==2.5.3
httpx==0.26.0
REQEOF

# ── Dockerfile ───────────────────────────────────────────────────────────────

cat > "$VERTICAL_DIR/Dockerfile" << DKEOF
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml README.md ./
COPY packages ./packages
RUN pip install --no-cache-dir .

COPY services/verticals/${VERTICAL_NAME} ./services/verticals/${VERTICAL_NAME}

WORKDIR /app/services/verticals/${VERTICAL_NAME}

ENV PYTHONPATH=/app
ENV APP_ENV=production

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
DKEOF

# ── Append to docker-compose.yml ─────────────────────────────────────────────

# Check if service already in docker-compose
if grep -q "^  ${SERVICE_NAME}:" "$REPO_ROOT/docker-compose.yml" 2>/dev/null; then
    echo "WARNING: Service '${SERVICE_NAME}' already in docker-compose.yml — skipping"
else
    # Insert before the volumes: section
    cat >> "$REPO_ROOT/docker-compose.yml.tmp" << DCEOF

  ${SERVICE_NAME}:
    build:
      context: .
      dockerfile: services/verticals/${VERTICAL_NAME}/Dockerfile
    depends_on:
      - core
    environment:
      CORE_SERVICE_URL: http://core:8000
      APP_ENV: development
    ports:
      - "${PORT}:8000"
DCEOF

    # Insert the new service block before 'volumes:' line
    sed -i "/^volumes:/e cat $REPO_ROOT/docker-compose.yml.tmp" "$REPO_ROOT/docker-compose.yml"
    rm -f "$REPO_ROOT/docker-compose.yml.tmp"
    echo "Added '${SERVICE_NAME}' to docker-compose.yml on port ${PORT}"
fi

# ── Summary ──────────────────────────────────────────────────────────────────

echo ""
echo "✓ Vertical '$VERTICAL_NAME' created at:"
echo "  $VERTICAL_DIR/"
echo ""
echo "Files:"
echo "  app/main.py        — FastAPI app with VerticalBase"
echo "  app/__init__.py"
echo "  requirements.txt"
echo "  Dockerfile"
echo ""
echo "Next steps:"
echo "  1. Edit app/main.py — add routes, event handlers, capabilities"
echo "  2. docker-compose up -d ${SERVICE_NAME}"
echo "  3. Verify registration: curl http://localhost:3000/registry/services/${VERTICAL_NAME}"
echo "  4. Access via gateway: curl http://localhost:8000/v1/verticals/${VERTICAL_NAME}/"
echo ""
